[package]
name = "gfx_static_mesh"
version = "0.0.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.15"
winit = "0.25"

component = { path = "../component" }
data = { path = "../data" }
entity = { path = "../entity" }
event = { path = "../event" }
vulkan = { path = "../vulkan" }
