[package]
name = "gfx_camera"
version = "0.0.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.15"

component = { path = "../component" }
entity = { path = "../entity" }
event = { path = "../event" }
gfx = { path = "../gfx" }
